In [1]:
import numpy as np
import warnings
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [2]:
warnings.filterwarnings("ignore")

In [3]:
dataset = pd.read_csv("Preprocessed_Dataset_Numerical.csv")

In [4]:
dataset

,Age,Income,LoanAmount,CreditScore,InterestRate,LoanTerm,Education_High School,Education_Master's,Education_PhD,EmploymentType_Part-time,EmploymentType_Self-employed,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,Default
0,57.0,109874.0,30973.0,567.0,13.95,60.0,0,0,0,1,0,0,0,0,0,0,0,0,0
1,69.0,34006.0,112148.0,597.0,10.60,24.0,0,0,0,1,0,0,1,0,0,0,0,0,1
2,20.0,36779.0,135741.0,352.0,23.82,36.0,0,0,0,0,0,0,0,0,0,0,0,0,1
3,41.0,50628.0,82083.0,828.0,11.32,48.0,1,0,0,0,0,0,0,0,0,0,0,0,1
4,28.0,114840.0,246968.0,415.0,22.65,24.0,1,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934.0,105532.0,521.0,14.66,24.0,0,0,0,0,0,0,1,0,0,0,0,0,1
49996,47.0,139079.0,102610.0,669.0,17.28,24.0,0,0,0,0,0,1,0,0,0,0,0,0,0
49997,32.0,106367.0,85207.0,466.0,2.44,36.0,0,0,0,0,0,0,0,0,0,0,0,0,0
49998,29.0,94936.0,45806.0,313.0,24.81,48.0,0,0,0,0,0,0,0,1,0,0,0,0,1
49999,28.0,115166.0,211439.0,461.0,24.79,60.0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [5]:
independent = dataset.drop("Default",axis = 1)
dependent = dataset["Default"]

In [6]:
independent

,Age,Income,LoanAmount,CreditScore,InterestRate,LoanTerm,Education_High School,Education_Master's,Education_PhD,EmploymentType_Part-time,EmploymentType_Self-employed,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other
0,57.0,109874.0,30973.0,567.0,13.95,60.0,0,0,0,1,0,0,0,0,0,0,0,0
1,69.0,34006.0,112148.0,597.0,10.60,24.0,0,0,0,1,0,0,1,0,0,0,0,0
2,20.0,36779.0,135741.0,352.0,23.82,36.0,0,0,0,0,0,0,0,0,0,0,0,0
3,41.0,50628.0,82083.0,828.0,11.32,48.0,1,0,0,0,0,0,0,0,0,0,0,0
4,28.0,114840.0,246968.0,415.0,22.65,24.0,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934.0,105532.0,521.0,14.66,24.0,0,0,0,0,0,0,1,0,0,0,0,0
49996,47.0,139079.0,102610.0,669.0,17.28,24.0,0,0,0,0,0,1,0,0,0,0,0,0
49997,32.0,106367.0,85207.0,466.0,2.44,36.0,0,0,0,0,0,0,0,0,0,0,0,0
49998,29.0,94936.0,45806.0,313.0,24.81,48.0,0,0,0,0,0,0,0,1,0,0,0,0
49999,28.0,115166.0,211439.0,461.0,24.79,60.0,0,0,0,0,0,0,0,0,0,0,0,0

In [7]:
dependent

0        0
1        1
2        1
3        1
4        0
        ..
49995    1
49996    0
49997    0
49998    1
49999    1
Name: Default, Length: 50000, dtype: int64

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Age                           50000 non-null  float64
 1   Income                        50000 non-null  float64
 2   LoanAmount                    50000 non-null  float64
 3   CreditScore                   50000 non-null  float64
 4   InterestRate                  50000 non-null  float64
 5   LoanTerm                      50000 non-null  float64
 6   Education_High School         50000 non-null  int64
 7   Education_Master's            50000 non-null  int64
 8   Education_PhD                 50000 non-null  int64
 9   EmploymentType_Part-time      50000 non-null  int64
 10  EmploymentType_Self-employed  50000 non-null  int64
 11  EmploymentType_Unemployed     50000 non-null  int64
 12  MaritalStatus_Married         50000 non-null  int64
 13  MaritalStatus_Single          50000 non-null  int64
 14  LoanPurpose_Business          50000 non-null  int64
 15  LoanPurpose_Education         50000 non-null  int64
 16  LoanPurpose_Home              50000 non-null  int64
 17  LoanPurpose_Other             50000 non-null  int64
 18  Default                       50000 non-null  int64
dtypes: float64(6), int64(13)
memory usage: 7.2 MB

# Feature Selection

In [10]:
#Select K Best Algorithm
def selectKBest(n):
    kbest = SelectKBest(score_func  = chi2, k = n)
    kbestModel = kbest.fit(independent,dependent)
    features = kbest.transform(independent)
    return kbest,features

In [11]:
#Splitting into training and testing datasetsdef Split_To_Training_Testing(features):
    x_train, x_test, y_train, y_test = train_test_split(features,dependent,test_size = 0.20,random_state = 0)
    sc = StandardScaler()
    x_train = sc.fit_transform(x_train)
    x_test = sc.transform(x_test) 
    
    return x_train, x_test, y_train, y_test

In [58]:
algorithm_acc = {}

In [90]:
#Classificaiton Models
def build_model():   
    algorithm_acc.clear()
    logistic_regression(x_train,y_train,x_test,y_test)    
    svm_linear(x_train,y_train,x_test,y_test)
    svm_non_linear(x_train,y_train,x_test,y_test)
    knn_regresssion(x_train,y_train,x_test,y_test)
    decisionTree(x_train,y_train,x_test,y_test)
    naive_baye(x_train,y_train,x_test,y_test)
    random_forest(x_train,y_train,x_test,y_test)  
    #return lg_conf_matrix, lg_accuracy , lg_class_report 
    
def logistic_regression(x_train,y_train,x_test,y_test):  
    lg_regression = LogisticRegression(random_state = 42)
    lg_regression.fit(x_train,y_train)
    y_pred = lg_regression.predict(x_test)
    lg_cm = confusion_matrix(y_test, y_pred)
    lg_accuracy = accuracy_score(y_test, y_pred )
    lg_classification = classification_report(y_test, y_pred)   
    algorithm_acc["Logistic"] = lg_accuracy
  
def svm_linear(x_train,y_train,x_test,y_test):
    svm_regression = SVC(kernel = 'linear', random_state = 0)
    svm_regression.fit(x_train,y_train)
    y_pred = svm_regression.predict(x_test)
    svm_cm = confusion_matrix(y_test, y_pred)
    svm_accuracy = accuracy_score(y_test, y_pred )
    svm_classification = classification_report(y_test, y_pred)
    algorithm_acc["SVM LINEAR"] = svm_accuracy

def svm_non_linear(x_train,y_train,x_test,y_test):
    svmnl_regression = SVC(kernel = 'rbf', random_state = 0)
    svmnl_regression.fit(x_train,y_train)
    y_pred = svmnl_regression.predict(x_test)
    svmnl_cm = confusion_matrix(y_test, y_pred)
    svmnl_accuracy = accuracy_score(y_test, y_pred )
    svmnl_classification = classification_report(y_test, y_pred)
    algorithm_acc["SVM NON LINEAR"] = svmnl_accuracy    

def knn_regresssion(x_train,y_train,x_test,y_test):
    knn_regression =  KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    knn_regression.fit(x_train,y_train)
    y_pred = knn_regression.predict(x_test)
    knn_cm = confusion_matrix(y_test, y_pred)
    knn_accuracy = accuracy_score(y_test, y_pred )
    knn_classification = classification_report(y_test, y_pred)    
    algorithm_acc["KNN"] = knn_accuracy    

def decisionTree(x_train,y_train,x_test,y_test):    
    des_regression =  DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    des_regression.fit(x_train,y_train)
    y_pred = des_regression.predict(x_test)
    des_cm = confusion_matrix(y_test, y_pred)
    des_accuracy = accuracy_score(y_test, y_pred )
    des_classification = classification_report(y_test, y_pred)
    algorithm_acc["DECISION TREE"] = des_accuracy  

def naive_baye(x_train,y_train,x_test,y_test):    
    nav_regression = GaussianNB()
    nav_regression.fit(x_train,y_train)
    y_pred = nav_regression.predict(x_test)
    nav_cm = confusion_matrix(y_test, y_pred)
    nav_accuracy = accuracy_score(y_test, y_pred )
    nav_classification = classification_report(y_test, y_pred)
    algorithm_acc["NAIVE BAYE"] = nav_accuracy 

    
def random_forest(x_train,y_train,x_test,y_test):
    rf_regression = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    rf_regression.fit(x_train,y_train)
    y_pred = rf_regression.predict(x_test)
    rf_cm = confusion_matrix(y_test, y_pred)
    rf_accuracy = accuracy_score(y_test, y_pred )
    rf_classification = classification_report(y_test, y_pred)
    algorithm_acc["RANDOM FOREST"] = rf_accuracy

In [66]:
# K = 7
kbest,features = selectKBest(7)
kbest

SelectKBest(k=7, score_func=<function chi2 at 0x000001DF44AC4720>)

In [68]:
features

array([[5.70000e+01, 1.09874e+05, 3.09730e+04, ..., 1.39500e+01,
        0.00000e+00, 0.00000e+00],
       [6.90000e+01, 3.40060e+04, 1.12148e+05, ..., 1.06000e+01,
        0.00000e+00, 1.00000e+00],
       [2.00000e+01, 3.67790e+04, 1.35741e+05, ..., 2.38200e+01,
        0.00000e+00, 0.00000e+00],
       ...,
       [3.20000e+01, 1.06367e+05, 8.52070e+04, ..., 2.44000e+00,
        0.00000e+00, 0.00000e+00],
       [2.90000e+01, 9.49360e+04, 4.58060e+04, ..., 2.48100e+01,
        0.00000e+00, 0.00000e+00],
       [2.80000e+01, 1.15166e+05, 2.11439e+05, ..., 2.47900e+01,
        0.00000e+00, 0.00000e+00]])

In [70]:
independent.columns[kbest.get_support()]

Index(['Age', 'Income', 'LoanAmount', 'CreditScore', 'InterestRate',
       'EmploymentType_Unemployed', 'MaritalStatus_Married'],
      dtype='object')

In [72]:
x_train,x_test, y_train, y_test = Split_To_Training_Testing(features)

In [74]:
#lg_conf_matrix, lg_accuracy , lg_class_report  = build_model()
build_model()

In [78]:
#k = 7
algorithm_acc

{'Logistic': 0.6546,
 'SVM LINEAR': 0.6544,
 'SVM NON LINEAR': 0.6657,
 'KNN': 0.6169,
 'DECISION TREE': 0.575,
 'NAIVE BAYE': 0.6589,
 'RANDOM FOREST': 0.6229}

In [92]:
# K = 15
kbest,features = selectKBest(15)
kbest

SelectKBest(k=15, score_func=<function chi2 at 0x000001DF44AC4720>)

In [94]:
independent.columns[kbest.get_support()]

Index(['Age', 'Income', 'LoanAmount', 'CreditScore', 'InterestRate',
       'LoanTerm', 'Education_High School', 'EmploymentType_Part-time',
       'EmploymentType_Unemployed', 'MaritalStatus_Married',
       'MaritalStatus_Single', 'LoanPurpose_Business', 'LoanPurpose_Education',
       'LoanPurpose_Home', 'LoanPurpose_Other'],
      dtype='object')

In [96]:
x_train,x_test, y_train, y_test = Split_To_Training_Testing(features)

In [98]:
build_model()

In [99]:
algorithm_acc

{'Logistic': 0.6589,
 'SVM LINEAR': 0.658,
 'SVM NON LINEAR': 0.6613,
 'KNN': 0.6131,
 'DECISION TREE': 0.5788,
 'NAIVE BAYE': 0.6578,
 'RANDOM FOREST': 0.6202}