In [74]:
#Importing Libraries
import warnings
from utility import Univariate
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [76]:
warnings.filterwarnings("ignore")

In [78]:
#Loading Dataset
dataset = pd.read_csv("Balanced_Dataset.csv")

In [80]:
dataset

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,57.0,109874,30973,567,113,4,13.95,60,0.62,Master's,Part-time,Divorced,Yes,Yes,Auto,No,0
1,69.0,34006,112148,597,10,4,10.60,24,0.41,Master's,Part-time,Married,No,Yes,Home,Yes,1
2,20.0,36779,135741,352,75,4,23.82,36,0.84,Bachelor's,Full-time,Divorced,Yes,No,Auto,No,1
3,41.0,50628,82083,828,102,1,11.32,48,0.46,High School,Self-employed,Divorced,Yes,No,Auto,No,1
4,28.0,114840,246968,415,109,4,22.65,24,0.73,High School,Self-employed,Divorced,No,Yes,Home,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934,105532,521,31,3,14.66,24,0.48,Bachelor's,Self-employed,Married,No,Yes,Business,Yes,1
49996,47.0,139079,102610,669,82,3,17.28,24,0.21,PhD,Unemployed,Divorced,Yes,Yes,Auto,No,0
49997,32.0,106367,85207,466,34,1,2.44,36,0.83,Bachelor's,Self-employed,Divorced,Yes,No,Business,No,0
49998,29.0,94936,45806,313,44,4,24.81,48,0.83,PhD,Full-time,Single,Yes,Yes,Home,Yes,1
49999,28.0,115166,211439,461,41,1,24.79,60,0.59,Master's,Full-time,Divorced,No,Yes,Other,Yes,1

In [82]:
dataset.isnull().sum()

Age               1
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       2
HasDependents     0
LoanPurpose       1
HasCoSigner       0
Default           0
dtype: int64

In [84]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             49999 non-null  float64
 1   Income          50000 non-null  int64
 2   LoanAmount      50000 non-null  int64
 3   CreditScore     50000 non-null  int64
 4   MonthsEmployed  50000 non-null  int64
 5   NumCreditLines  50000 non-null  int64
 6   InterestRate    50000 non-null  float64
 7   LoanTerm        50000 non-null  int64
 8   DTIRatio        50000 non-null  float64
 9   Education       50000 non-null  object
 10  EmploymentType  50000 non-null  object
 11  MaritalStatus   50000 non-null  object
 12  HasMortgage     49998 non-null  object
 13  HasDependents   50000 non-null  object
 14  LoanPurpose     49999 non-null  object
 15  HasCoSigner     50000 non-null  object
 16  Default         50000 non-null  int64
dtypes: float64(3), int64(7), object(7)
memory usage: 6.5+ MB

In [86]:
independent = dataset.drop(["Default","DTIRatio","HasCoSigner","HasDependents","HasMortgage","MonthsEmployed","NumCreditLines"], axis = 1)
dependent = dataset["Default"]

In [88]:
dependent

0        0
1        1
2        1
3        1
4        0
        ..
49995    1
49996    0
49997    0
49998    1
49999    1
Name: Default, Length: 50000, dtype: int64

In [90]:
independent

,Age,Income,LoanAmount,CreditScore,InterestRate,LoanTerm,Education,EmploymentType,MaritalStatus,LoanPurpose
0,57.0,109874,30973,567,13.95,60,Master's,Part-time,Divorced,Auto
1,69.0,34006,112148,597,10.60,24,Master's,Part-time,Married,Home
2,20.0,36779,135741,352,23.82,36,Bachelor's,Full-time,Divorced,Auto
3,41.0,50628,82083,828,11.32,48,High School,Self-employed,Divorced,Auto
4,28.0,114840,246968,415,22.65,24,High School,Self-employed,Divorced,Home
...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934,105532,521,14.66,24,Bachelor's,Self-employed,Married,Business
49996,47.0,139079,102610,669,17.28,24,PhD,Unemployed,Divorced,Auto
49997,32.0,106367,85207,466,2.44,36,Bachelor's,Self-employed,Divorced,Business
49998,29.0,94936,45806,313,24.81,48,PhD,Full-time,Single,Home
49999,28.0,115166,211439,461,24.79,60,Master's,Full-time,Divorced,Other

In [92]:
#Splitting into Numerical and Categorical Data
numerical_data = independent.select_dtypes(include = [np.number])
categorical_data = independent.select_dtypes(exclude = [np.number])

In [94]:
categorical_data

         Education EmploymentType MaritalStatus LoanPurpose
0         Master's      Part-time      Divorced        Auto
1         Master's      Part-time       Married        Home
2       Bachelor's      Full-time      Divorced        Auto
3      High School  Self-employed      Divorced        Auto
4      High School  Self-employed      Divorced        Home
...            ...            ...           ...         ...
49995   Bachelor's  Self-employed       Married    Business
49996          PhD     Unemployed      Divorced        Auto
49997   Bachelor's  Self-employed      Divorced    Business
49998          PhD      Full-time        Single        Home
49999     Master's      Full-time      Divorced       Other

[50000 rows x 4 columns]

In [96]:
numerical_data

        Age  Income  LoanAmount  CreditScore  InterestRate  LoanTerm
0      57.0  109874       30973          567         13.95        60
1      69.0   34006      112148          597         10.60        24
2      20.0   36779      135741          352         23.82        36
3      41.0   50628       82083          828         11.32        48
4      28.0  114840      246968          415         22.65        24
...     ...     ...         ...          ...           ...       ...
49995  20.0  143934      105532          521         14.66        24
49996  47.0  139079      102610          669         17.28        24
49997  32.0  106367       85207          466          2.44        36
49998  29.0   94936       45806          313         24.81        48
49999  28.0  115166      211439          461         24.79        60

[50000 rows x 6 columns]

In [98]:
imputer = SimpleImputer(strategy = "mean")

In [100]:
imputer.fit(numerical_data[::])

SimpleImputer()

In [102]:
numerical_filled_data = pd.DataFrame(imputer.fit_transform(numerical_data), columns = numerical_data.columns)

In [104]:
numerical_filled_data.isnull().sum()

Age             0
Income          0
LoanAmount      0
CreditScore     0
InterestRate    0
LoanTerm        0
dtype: int64

In [106]:
categorical_imputer = SimpleImputer(strategy = "most_frequent")

In [108]:
categorical_filled_data = pd.DataFrame(categorical_imputer.fit_transform(categorical_data), columns = categorical_data.columns)

In [110]:
categorical_filled_data.isnull().sum()

Education         0
EmploymentType    0
MaritalStatus     0
LoanPurpose       0
dtype: int64

In [112]:
independent = pd.concat([numerical_filled_data,categorical_filled_data], axis = 1)

In [114]:
independent

,Age,Income,LoanAmount,CreditScore,InterestRate,LoanTerm,Education,EmploymentType,MaritalStatus,LoanPurpose
0,57.0,109874.0,30973.0,567.0,13.95,60.0,Master's,Part-time,Divorced,Auto
1,69.0,34006.0,112148.0,597.0,10.60,24.0,Master's,Part-time,Married,Home
2,20.0,36779.0,135741.0,352.0,23.82,36.0,Bachelor's,Full-time,Divorced,Auto
3,41.0,50628.0,82083.0,828.0,11.32,48.0,High School,Self-employed,Divorced,Auto
4,28.0,114840.0,246968.0,415.0,22.65,24.0,High School,Self-employed,Divorced,Home
...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934.0,105532.0,521.0,14.66,24.0,Bachelor's,Self-employed,Married,Business
49996,47.0,139079.0,102610.0,669.0,17.28,24.0,PhD,Unemployed,Divorced,Auto
49997,32.0,106367.0,85207.0,466.0,2.44,36.0,Bachelor's,Self-employed,Divorced,Business
49998,29.0,94936.0,45806.0,313.0,24.81,48.0,PhD,Full-time,Single,Home
49999,28.0,115166.0,211439.0,461.0,24.79,60.0,Master's,Full-time,Divorced,Other

In [116]:
independent.isnull().sum()

Age               0
Income            0
LoanAmount        0
CreditScore       0
InterestRate      0
LoanTerm          0
Education         0
EmploymentType    0
MaritalStatus     0
LoanPurpose       0
dtype: int64

In [118]:
dependent

0        0
1        1
2        1
3        1
4        0
        ..
49995    1
49996    0
49997    0
49998    1
49999    1
Name: Default, Length: 50000, dtype: int64

In [120]:
preprocessed_dataset = pd.concat([independent, dependent],axis = 1)
preprocessed_dataset

,Age,Income,LoanAmount,CreditScore,InterestRate,LoanTerm,Education,EmploymentType,MaritalStatus,LoanPurpose,Default
0,57.0,109874.0,30973.0,567.0,13.95,60.0,Master's,Part-time,Divorced,Auto,0
1,69.0,34006.0,112148.0,597.0,10.60,24.0,Master's,Part-time,Married,Home,1
2,20.0,36779.0,135741.0,352.0,23.82,36.0,Bachelor's,Full-time,Divorced,Auto,1
3,41.0,50628.0,82083.0,828.0,11.32,48.0,High School,Self-employed,Divorced,Auto,1
4,28.0,114840.0,246968.0,415.0,22.65,24.0,High School,Self-employed,Divorced,Home,0
...,...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934.0,105532.0,521.0,14.66,24.0,Bachelor's,Self-employed,Married,Business,1
49996,47.0,139079.0,102610.0,669.0,17.28,24.0,PhD,Unemployed,Divorced,Auto,0
49997,32.0,106367.0,85207.0,466.0,2.44,36.0,Bachelor's,Self-employed,Divorced,Business,0
49998,29.0,94936.0,45806.0,313.0,24.81,48.0,PhD,Full-time,Single,Home,1
49999,28.0,115166.0,211439.0,461.0,24.79,60.0,Master's,Full-time,Divorced,Other,1

In [122]:
preprocessed_dataset.to_csv("Preprocessed_Dataset.csv",index = False)

# Converting Categorical to Numerical Dataset

In [124]:
independent = pd.get_dummies(independent,dtype= int,drop_first = True)
independent

,Age,Income,LoanAmount,CreditScore,InterestRate,LoanTerm,Education_High School,Education_Master's,Education_PhD,EmploymentType_Part-time,EmploymentType_Self-employed,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other
0,57.0,109874.0,30973.0,567.0,13.95,60.0,0,1,0,1,0,0,0,0,0,0,0,0
1,69.0,34006.0,112148.0,597.0,10.60,24.0,0,1,0,1,0,0,1,0,0,0,1,0
2,20.0,36779.0,135741.0,352.0,23.82,36.0,0,0,0,0,0,0,0,0,0,0,0,0
3,41.0,50628.0,82083.0,828.0,11.32,48.0,1,0,0,0,1,0,0,0,0,0,0,0
4,28.0,114840.0,246968.0,415.0,22.65,24.0,1,0,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934.0,105532.0,521.0,14.66,24.0,0,0,0,0,1,0,1,0,1,0,0,0
49996,47.0,139079.0,102610.0,669.0,17.28,24.0,0,0,1,0,0,1,0,0,0,0,0,0
49997,32.0,106367.0,85207.0,466.0,2.44,36.0,0,0,0,0,1,0,0,0,1,0,0,0
49998,29.0,94936.0,45806.0,313.0,24.81,48.0,0,0,1,0,0,0,0,1,0,0,1,0
49999,28.0,115166.0,211439.0,461.0,24.79,60.0,0,1,0,0,0,0,0,0,0,0,0,1

In [126]:
preprocessed_dataset_numerical = pd.concat([independent, dependent],axis = 1)
preprocessed_dataset_numerical

,Age,Income,LoanAmount,CreditScore,InterestRate,LoanTerm,Education_High School,Education_Master's,Education_PhD,EmploymentType_Part-time,EmploymentType_Self-employed,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,Default
0,57.0,109874.0,30973.0,567.0,13.95,60.0,0,1,0,1,0,0,0,0,0,0,0,0,0
1,69.0,34006.0,112148.0,597.0,10.60,24.0,0,1,0,1,0,0,1,0,0,0,1,0,1
2,20.0,36779.0,135741.0,352.0,23.82,36.0,0,0,0,0,0,0,0,0,0,0,0,0,1
3,41.0,50628.0,82083.0,828.0,11.32,48.0,1,0,0,0,1,0,0,0,0,0,0,0,1
4,28.0,114840.0,246968.0,415.0,22.65,24.0,1,0,0,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934.0,105532.0,521.0,14.66,24.0,0,0,0,0,1,0,1,0,1,0,0,0,1
49996,47.0,139079.0,102610.0,669.0,17.28,24.0,0,0,1,0,0,1,0,0,0,0,0,0,0
49997,32.0,106367.0,85207.0,466.0,2.44,36.0,0,0,0,0,1,0,0,0,1,0,0,0,0
49998,29.0,94936.0,45806.0,313.0,24.81,48.0,0,0,1,0,0,0,0,1,0,0,1,0,1
49999,28.0,115166.0,211439.0,461.0,24.79,60.0,0,1,0,0,0,0,0,0,0,0,0,1,1

# Univariate Analysis

In [128]:
preprocessed_dataset_numerical.describe()

,Age,Income,LoanAmount,CreditScore,InterestRate,LoanTerm,Education_High School,Education_Master's,Education_PhD,EmploymentType_Part-time,EmploymentType_Self-employed,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,Default
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000
mean,40.527231,77895.918920,135393.102200,567.695860,14.546836,36.066240,0.26182,0.241400,0.241000,0.255080,0.248280,0.267420,0.321920,0.334420,0.20554,0.202120,0.190220,0.199920,0.500000
std,14.950361,40100.315275,70732.184109,158.921488,6.623192,16.963983,0.43963,0.427937,0.427695,0.435911,0.432019,0.442618,0.467217,0.471792,0.40410,0.401585,0.392479,0.399944,0.500005
min,18.000000,15004.000000,5000.000000,300.000000,2.000000,12.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
25%,27.000000,41732.000000,75429.250000,430.000000,8.970000,24.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
50%,39.000000,76332.500000,139267.000000,565.000000,15.055000,36.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.500000
75%,53.000000,112750.250000,197546.000000,704.000000,20.400000,48.000000,1.00000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.00000,0.000000,0.000000,0.000000,1.000000
max,69.000000,149999.000000,249993.000000,849.000000,25.000000,60.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000

In [130]:
obj = Univariate()
tble = obj.getUnivarateTbl(preprocessed_dataset_numerical, preprocessed_dataset_numerical.columns)
tble

,Age,Income,LoanAmount,CreditScore,InterestRate,LoanTerm,Education_High School,Education_Master's,Education_PhD,EmploymentType_Part-time,EmploymentType_Self-employed,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,Default
Mean,40.527231,77895.91892,135393.1022,567.69586,14.546836,36.06624,0.26182,0.2414,0.241,0.25508,0.24828,0.26742,0.32192,0.33442,0.20554,0.20212,0.19022,0.19992,0.5
Median,39.0,76332.5,139267.0,565.0,15.055,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5
Mode,22.0,15293.0,206276.0,513.0,21.93,60.0,0,0,0,0,0,0,0,0,0,0,0,0,0
Q1:25%,27.0,41732.0,75429.25,430.0,8.97,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Q2:50%,39.0,76332.5,139267.0,565.0,15.055,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5
Q3:75%,53.0,112750.25,197546.0,704.0,20.4,48.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
Q4:100%,69.0,149999.0,249993.0,849.0,25.0,60.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
IQR,26.0,71018.25,122116.75,274.0,11.43,24.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
1.5Rule,39.0,106527.375,183175.125,411.0,17.145,36.0,1.5,0.0,0.0,1.5,0.0,1.5,1.5,1.5,0.0,0.0,0.0,0.0,1.5
Lesser,-12.0,-64795.375,-107745.875,19.0,-8.175,-12.0,-1.5,0.0,0.0,-1.5,0.0,-1.5,-1.5,-1.5,0.0,0.0,0.0,0.0,-1.5
Greater,92.0,219277.625,380721.125,1115.0,37.545,84.0,2.5,0.0,0.0,2.5,0.0,2.5,2.5,2.5,0.0,0.0,0.0,0.0,2.5
Minimum,18.0,15004.0,5000.0,300.0,2.0,12.0,0,0,0,0,0,0,0,0,0,0,0,0,0
Maximum,69.0,149999.0,249993.0,849.0,25.0,60.0,1,1,1,1,1,1,1,1,1,1,1,1,1
Skew,0.247032,0.108298,-0.133718,0.053522,-0.18543,0.000646,1.083592,1.208639,1.211193,1.123762,1.165365,1.050971,0.762331,0.701948,1.457421,1.48358,1.578646,1.50067,0.0
Kurtosis,-1.128344,-1.238248,-1.183745,-1.19343,-1.16559,-1.298216,-0.825862,-0.539214,-0.533033,-0.737189,-0.641951,-0.895495,-1.418908,-1.50733,0.124082,0.201017,0.492143,0.252021,-2.00008
Variance,223.513284,1608035285.146601,5003041868.799876,25256.03944,43.866669,287.776728,0.193274,0.18313,0.182923,0.190018,0.186641,0.19591,0.218292,0.222588,0.163297,0.161271,0.154039,0.159955,0.250005
STD,14.950361,40100.315275,70732.184109,158.921488,6.623192,16.963983,0.43963,0.427937,0.427695,0.435911,0.432019,0.442618,0.467217,0.471792,0.4041,0.401585,0.392479,0.399944,0.500005

In [131]:
#Finding Outliers
lesser_outlier = []
greater_outlier = []
for column in preprocessed_dataset_numerical.columns:
  
    if tble[column]["Minimum"] < tble[column]["Lesser"] :
        lesser_outlier.append(column)
    
    if tble[column]["Maximum"] > tble[column]["Greater"]:
        greater_outlier.append(column)     

print(lesser_outlier)
print(greater_outlier)

[]
["Education_Master's", 'Education_PhD', 'EmploymentType_Self-employed', 'LoanPurpose_Business', 'LoanPurpose_Education', 'LoanPurpose_Home', 'LoanPurpose_Other']

In [132]:
#Removing the Outliers by replacing the lesser and greater values
for column in lesser_outlier:
    preprocessed_dataset_numerical[column][preprocessed_dataset_numerical[column] < tble[column]["Lesser"]] = tble[column]["Lesser"]

for column in greater_outlier: 
    preprocessed_dataset_numerical[column][preprocessed_dataset_numerical[column] > tble[column]["Greater"]] = tble[column]["Greater"]

In [34]:
tble = obj.getUnivarateTbl(preprocessed_dataset_numerical, preprocessed_dataset_numerical.columns)
tble

,Age,Income,LoanAmount,CreditScore,InterestRate,LoanTerm,Education_High School,Education_Master's,Education_PhD,EmploymentType_Part-time,EmploymentType_Self-employed,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,Default
Mean,40.527231,77895.91892,135393.1022,567.69586,14.546836,36.06624,0.26182,0.0,0.0,0.25508,0.0,0.26742,0.32192,0.33442,0.0,0.0,0.0,0.0,0.5
Median,39.0,76332.5,139267.0,565.0,15.055,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5
Mode,22.0,15293.0,206276.0,513.0,21.93,60.0,0,0,0,0,0,0,0,0,0,0,0,0,0
Q1:25%,27.0,41732.0,75429.25,430.0,8.97,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Q2:50%,39.0,76332.5,139267.0,565.0,15.055,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5
Q3:75%,53.0,112750.25,197546.0,704.0,20.4,48.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
Q4:100%,69.0,149999.0,249993.0,849.0,25.0,60.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
IQR,26.0,71018.25,122116.75,274.0,11.43,24.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
1.5Rule,39.0,106527.375,183175.125,411.0,17.145,36.0,1.5,0.0,0.0,1.5,0.0,1.5,1.5,1.5,0.0,0.0,0.0,0.0,1.5
Lesser,-12.0,-64795.375,-107745.875,19.0,-8.175,-12.0,-1.5,0.0,0.0,-1.5,0.0,-1.5,-1.5,-1.5,0.0,0.0,0.0,0.0,-1.5
Greater,92.0,219277.625,380721.125,1115.0,37.545,84.0,2.5,0.0,0.0,2.5,0.0,2.5,2.5,2.5,0.0,0.0,0.0,0.0,2.5
Minimum,18.0,15004.0,5000.0,300.0,2.0,12.0,0,0,0,0,0,0,0,0,0,0,0,0,0
Maximum,69.0,149999.0,249993.0,849.0,25.0,60.0,1,0,0,1,0,1,1,1,0,0,0,0,1
Skew,0.247032,0.108298,-0.133718,0.053522,-0.18543,0.000646,1.083592,0.0,0.0,1.123762,0.0,1.050971,0.762331,0.701948,0.0,0.0,0.0,0.0,0.0
Kurtosis,-1.128344,-1.238248,-1.183745,-1.19343,-1.16559,-1.298216,-0.825862,0.0,0.0,-0.737189,0.0,-0.895495,-1.418908,-1.50733,0.0,0.0,0.0,0.0,-2.00008
Variance,223.513284,1608035285.146601,5003041868.799876,25256.03944,43.866669,287.776728,0.193274,0.0,0.0,0.190018,0.0,0.19591,0.218292,0.222588,0.0,0.0,0.0,0.0,0.250005
STD,14.950361,40100.315275,70732.184109,158.921488,6.623192,16.963983,0.43963,0.0,0.0,0.435911,0.0,0.442618,0.467217,0.471792,0.0,0.0,0.0,0.0,0.500005

In [136]:
#Cross checking Outliers
lesser_outlier = []
greater_outlier = []
for column in preprocessed_dataset_numerical.columns:
  
    if tble[column]["Minimum"] < tble[column]["Lesser"] :
        lesser_outlier.append(column)
    
    if tble[column]["Maximum"] > tble[column]["Greater"]:
        greater_outlier.append(column)     

print(lesser_outlier)
print(greater_outlier)

[]
["Education_Master's", 'Education_PhD', 'EmploymentType_Self-employed', 'LoanPurpose_Business', 'LoanPurpose_Education', 'LoanPurpose_Home', 'LoanPurpose_Other']

In [138]:
preprocessed_dataset_numerical.isnull().sum()

Age                             0
Income                          0
LoanAmount                      0
CreditScore                     0
InterestRate                    0
LoanTerm                        0
Education_High School           0
Education_Master's              0
Education_PhD                   0
EmploymentType_Part-time        0
EmploymentType_Self-employed    0
EmploymentType_Unemployed       0
MaritalStatus_Married           0
MaritalStatus_Single            0
LoanPurpose_Business            0
LoanPurpose_Education           0
LoanPurpose_Home                0
LoanPurpose_Other               0
Default                         0
dtype: int64

In [140]:
preprocessed_dataset_numerical.to_csv("Preprocessed_Dataset_Numerical.csv",index = False)