In [1]:
import numpy as np
import warnings
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [2]:
warnings.filterwarnings("ignore")

In [3]:
dataset = pd.read_csv("Preprocessed_Dataset_Numerical.csv")

In [4]:
dataset

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education_High School,...,MaritalStatus_Married,MaritalStatus_Single,HasMortgage_Yes,HasDependents_Yes,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,HasCoSigner_Yes,Default
0,48.0,90754.0,5902.0,462.0,91.0,2.0,10.46,60.0,0.80,0,...,1,0,0,0,0,0,0,0,1,0
1,24.0,59193.0,90049.0,309.0,73.0,1.0,20.85,36.0,0.88,1,...,0,1,1,0,0,0,0,0,1,0
2,55.0,77343.0,204141.0,423.0,19.0,2.0,17.66,48.0,0.49,0,...,0,0,1,0,0,0,0,0,1,0
3,18.0,25087.0,15645.0,474.0,23.0,4.0,20.95,48.0,0.58,0,...,0,0,0,0,0,0,0,0,1,0
4,31.0,33215.0,235022.0,771.0,67.0,3.0,10.53,36.0,0.90,0,...,0,1,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,59.0,127901.0,46482.0,424.0,44.0,4.0,15.27,60.0,0.58,0,...,0,0,0,1,0,0,0,0,0,1
996,54.0,139677.0,138362.0,780.0,27.0,3.0,11.82,24.0,0.49,0,...,0,1,1,0,0,0,0,0,0,1
997,42.0,53038.0,62256.0,763.0,116.0,3.0,2.55,36.0,0.54,0,...,0,0,1,0,0,0,0,0,1,0
998,43.0,137420.0,116698.0,424.0,21.0,4.0,9.43,36.0,0.85,0,...,0,0,0,0,0,0,0,0,0,1
999,48.0,33362.0,205046.0,750.0,2.0,2.0,4.37,60.0,0.37,1,...,1,0,0,0,0,0,0,0,1,1

In [5]:
independent = dataset.drop("Default",axis = 1)
dependent = dataset["Default"]

In [6]:
independent

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education_High School,...,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,HasMortgage_Yes,HasDependents_Yes,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,HasCoSigner_Yes
0,48.0,90754.0,5902.0,462.0,91.0,2.0,10.46,60.0,0.80,0,...,0,1,0,0,0,0,0,0,0,1
1,24.0,59193.0,90049.0,309.0,73.0,1.0,20.85,36.0,0.88,1,...,0,0,1,1,0,0,0,0,0,1
2,55.0,77343.0,204141.0,423.0,19.0,2.0,17.66,48.0,0.49,0,...,0,0,0,1,0,0,0,0,0,1
3,18.0,25087.0,15645.0,474.0,23.0,4.0,20.95,48.0,0.58,0,...,0,0,0,0,0,0,0,0,0,1
4,31.0,33215.0,235022.0,771.0,67.0,3.0,10.53,36.0,0.90,0,...,0,0,1,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,59.0,127901.0,46482.0,424.0,44.0,4.0,15.27,60.0,0.58,0,...,0,0,0,0,1,0,0,0,0,0
996,54.0,139677.0,138362.0,780.0,27.0,3.0,11.82,24.0,0.49,0,...,0,0,1,1,0,0,0,0,0,0
997,42.0,53038.0,62256.0,763.0,116.0,3.0,2.55,36.0,0.54,0,...,0,0,0,1,0,0,0,0,0,1
998,43.0,137420.0,116698.0,424.0,21.0,4.0,9.43,36.0,0.85,0,...,0,0,0,0,0,0,0,0,0,0
999,48.0,33362.0,205046.0,750.0,2.0,2.0,4.37,60.0,0.37,1,...,1,1,0,0,0,0,0,0,0,1

In [7]:
dependent

0      0
1      0
2      0
3      0
4      1
      ..
995    1
996    1
997    0
998    1
999    1
Name: Default, Length: 1000, dtype: int64

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Age                           1000 non-null   float64
 1   Income                        1000 non-null   float64
 2   LoanAmount                    1000 non-null   float64
 3   CreditScore                   1000 non-null   float64
 4   MonthsEmployed                1000 non-null   float64
 5   NumCreditLines                1000 non-null   float64
 6   InterestRate                  1000 non-null   float64
 7   LoanTerm                      1000 non-null   float64
 8   DTIRatio                      1000 non-null   float64
 9   Education_High School         1000 non-null   int64
 10  Education_Master's            1000 non-null   int64
 11  Education_PhD                 1000 non-null   int64
 12  EmploymentType_Part-time      1000 non-null   int64
 13  EmploymentType_Self-employed  1000 non-null   int64
 14  EmploymentType_Unemployed     1000 non-null   int64
 15  MaritalStatus_Married         1000 non-null   int64
 16  MaritalStatus_Single          1000 non-null   int64
 17  HasMortgage_Yes               1000 non-null   int64
 18  HasDependents_Yes             1000 non-null   int64
 19  LoanPurpose_Business          1000 non-null   int64
 20  LoanPurpose_Education         1000 non-null   int64
 21  LoanPurpose_Home              1000 non-null   int64
 22  LoanPurpose_Other             1000 non-null   int64
 23  HasCoSigner_Yes               1000 non-null   int64
 24  Default                       1000 non-null   int64
dtypes: float64(9), int64(16)
memory usage: 195.4 KB

# Feature Selection

In [9]:
#Select K Best Algorithm
def selectKBest(n):
    kbest = SelectKBest(score_func  = chi2, k = n)
    kbestModel = kbest.fit(independent,dependent)
    features = kbest.transform(independent)
    return kbest,features

In [10]:
#Splitting into training and testing datasets
def Split_To_Training_Testing(features):
    x_train, x_test, y_train, y_test = train_test_split(features,dependent,test_size = 0.20,random_state = 0)
    sc = StandardScaler()
    x_train = sc.fit_transform(x_train)
    x_test = sc.transform(x_test) 
    
    return x_train, x_test, y_train, y_test

In [88]:
#Classificaiton Models
def build_model():   
    logistic_regression()    
    svm_linear()
    svm_non_linear()
    knn_regresssion()
    decisionTree()
    naive_baye()
    random_forest()  
    #return lg_conf_matrix, lg_accuracy , lg_class_report 
    
def logistic_regression():  
    lg_regression = LogisticRegression(random_state = 42)
    lg_regression.fit(x_train,y_train)
    y_pred = lg_regression.predict(x_test)
    lg_cm = confusion_matrix(y_test, y_pred)
    lg_accuracy = accuracy_score(y_test, y_pred )
    lg_classification = classification_report(y_test, y_pred)    
    print("Logistic Regression")
    print(lg_cm,"\n")    
    print(lg_accuracy,"\n")    
    print(lg_classification,"\n")    
    #return lg_cm, lg_accuracy, lg_classification

def svm_linear():
    svm_regression = SVC(kernel = 'linear', random_state = 0)
    svm_regression.fit(x_train,y_train)
    y_pred = svm_regression.predict(x_test)
    svm_cm = confusion_matrix(y_test, y_pred)
    svm_accuracy = accuracy_score(y_test, y_pred )
    svm_classification = classification_report(y_test, y_pred)
    print("SVM Linear")
    print(svm_cm,"\n")    
    print(svm_accuracy,"\n")    
    print(svm_classification,"\n")    
    
def svm_non_linear():
    svmnl_regression = SVC(kernel = 'rbf', random_state = 0)
    svmnl_regression.fit(x_train,y_train)
    y_pred = svmnl_regression.predict(x_test)
    svmnl_cm = confusion_matrix(y_test, y_pred)
    svmnl_accuracy = accuracy_score(y_test, y_pred )
    svmnl_classification = classification_report(y_test, y_pred)
    print("SVM NON Linear")
    print(svmnl_cm,"\n")    
    print(svmnl_accuracy,"\n")    
    print(svmnl_classification,"\n")    
    
def knn_regresssion():
    knn_regression =  KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    knn_regression.fit(x_train,y_train)
    y_pred = knn_regression.predict(x_test)
    knn_cm = confusion_matrix(y_test, y_pred)
    knn_accuracy = accuracy_score(y_test, y_pred )
    knn_classification = classification_report(y_test, y_pred)  
    print("KNN")
    print(knn_cm,"\n")    
    print(knn_accuracy,"\n")    
    print(knn_classification,"\n")    

    
def decisionTree():    
    des_regression =  DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    des_regression.fit(x_train,y_train)
    y_pred = des_regression.predict(x_test)
    des_cm = confusion_matrix(y_test, y_pred)
    des_accuracy = accuracy_score(y_test, y_pred )
    des_classification = classification_report(y_test, y_pred)
    
def naive_baye():    
    nav_regression = GaussianNB()
    nav_regression.fit(x_train,y_train)
    y_pred = nav_regression.predict(x_test)
    nav_cm = confusion_matrix(y_test, y_pred)
    nav_accuracy = accuracy_score(y_test, y_pred )
    nav_classification = classification_report(y_test, y_pred)
    print("Naive Baye")
    print(nav_cm,"\n")    
    print(nav_accuracy,"\n")    
    print(nav_classification,"\n")    

    
def random_forest():
    rf_regression = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    rf_regression.fit(x_train,y_train)
    y_pred = rf_regression.predict(x_test)
    rf_cm = confusion_matrix(y_test, y_pred)
    rf_accuracy = accuracy_score(y_test, y_pred )
    rf_classification = classification_report(y_test, y_pred)
    print("Random Forest")
    print(rf_cm,"\n")    
    print(rf_accuracy,"\n")    
    print(rf_classification,"\n")

In [89]:
# K = 7
kbest,features = selectKBest(10)
kbest

SelectKBest(score_func=<function chi2 at 0x000001C62DD20E00>)

In [90]:
features

array([[4.80000e+01, 9.07540e+04, 5.90200e+03, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [2.40000e+01, 5.91930e+04, 9.00490e+04, ..., 1.00000e+00,
        0.00000e+00, 1.00000e+00],
       [5.50000e+01, 7.73430e+04, 2.04141e+05, ..., 1.00000e+00,
        0.00000e+00, 1.00000e+00],
       ...,
       [4.20000e+01, 5.30380e+04, 6.22560e+04, ..., 1.00000e+00,
        0.00000e+00, 1.00000e+00],
       [4.30000e+01, 1.37420e+05, 1.16698e+05, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [4.80000e+01, 3.33620e+04, 2.05046e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00]])

In [91]:
independent.columns[kbest.get_support()]

Index(['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed',
       'InterestRate', 'EmploymentType_Unemployed', 'HasMortgage_Yes',
       'HasDependents_Yes', 'HasCoSigner_Yes'],
      dtype='object')

In [92]:
x_train,x_test, y_train, y_test = Split_To_Training_Testing(features)

In [93]:
#lg_conf_matrix, lg_accuracy , lg_class_report  = build_model()
build_model()

Logistic Regression
[[54 30]
 [45 71]]

0.625

              precision    recall  f1-score   support

           0       0.55      0.64      0.59        84
           1       0.70      0.61      0.65       116

    accuracy                           0.62       200
   macro avg       0.62      0.63      0.62       200
weighted avg       0.64      0.62      0.63       200


SVM Linear
[[53 31]
 [41 75]]

0.64

              precision    recall  f1-score   support

           0       0.56      0.63      0.60        84
           1       0.71      0.65      0.68       116

    accuracy                           0.64       200
   macro avg       0.64      0.64      0.64       200
weighted avg       0.65      0.64      0.64       200


SVM NON Linear
[[50 34]
 [42 74]]

0.62

              precision    recall  f1-score   support

           0       0.54      0.60      0.57        84
           1       0.69      0.64      0.66       116

    accuracy                           0.62       200
   macro avg       0.61      0.62      0.61       200
weighted avg       0.63      0.62      0.62       200


KNN
[[48 36]
 [46 70]]

0.59

              precision    recall  f1-score   support

           0       0.51      0.57      0.54        84
           1       0.66      0.60      0.63       116

    accuracy                           0.59       200
   macro avg       0.59      0.59      0.58       200
weighted avg       0.60      0.59      0.59       200


Naive Baye
[[58 26]
 [46 70]]

0.64

              precision    recall  f1-score   support

           0       0.56      0.69      0.62        84
           1       0.73      0.60      0.66       116

    accuracy                           0.64       200
   macro avg       0.64      0.65      0.64       200
weighted avg       0.66      0.64      0.64       200


Random Forest
[[60 24]
 [52 64]]

0.62

              precision    recall  f1-score   support

           0       0.54      0.71      0.61        84
           1       0.73      0.55      0.63       116

    accuracy                           0.62       200
   macro avg       0.63      0.63      0.62       200
weighted avg       0.65      0.62      0.62       200