In [37]:
import numpy as np
import pandas as pd
from sklearn.utils import shuffle

In [3]:
dataset = pd.read_csv("Loan_default.csv")

In [4]:
dataset

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56.0,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69.0,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46.0,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32.0,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60.0,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255342,8C6S86ESGC,19.0,37979,210682,541,109,4,14.11,12,0.85,Bachelor's,Full-time,Married,No,No,Other,No,0
255343,98R4KDHNND,32.0,51953,189899,511,14,2,11.55,24,0.21,High School,Part-time,Divorced,No,No,Home,No,1
255344,XQK1UUUNGP,56.0,84820,208294,597,70,3,5.29,60,0.50,High School,Self-employed,Married,Yes,Yes,Auto,Yes,0
255345,JAO28CPL4H,42.0,85109,60575,809,40,1,20.90,48,0.44,High School,Part-time,Single,Yes,Yes,Other,No,0
255346,ZTH91CGL0B,62.0,22418,18481,636,113,2,6.73,12,0.48,Bachelor's,Unemployed,Divorced,Yes,No,Education,Yes,0

In [6]:
new_data = dataset.copy()

In [7]:
new_data

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56.0,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69.0,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46.0,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32.0,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60.0,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255342,8C6S86ESGC,19.0,37979,210682,541,109,4,14.11,12,0.85,Bachelor's,Full-time,Married,No,No,Other,No,0
255343,98R4KDHNND,32.0,51953,189899,511,14,2,11.55,24,0.21,High School,Part-time,Divorced,No,No,Home,No,1
255344,XQK1UUUNGP,56.0,84820,208294,597,70,3,5.29,60,0.50,High School,Self-employed,Married,Yes,Yes,Auto,Yes,0
255345,JAO28CPL4H,42.0,85109,60575,809,40,1,20.90,48,0.44,High School,Part-time,Single,Yes,Yes,Other,No,0
255346,ZTH91CGL0B,62.0,22418,18481,636,113,2,6.73,12,0.48,Bachelor's,Unemployed,Divorced,Yes,No,Education,Yes,0

In [9]:
new_data.drop(["LoanID"],axis = 1,inplace = True)

In [10]:
new_data

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,56.0,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,69.0,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,46.0,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,32.0,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,60.0,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255342,19.0,37979,210682,541,109,4,14.11,12,0.85,Bachelor's,Full-time,Married,No,No,Other,No,0
255343,32.0,51953,189899,511,14,2,11.55,24,0.21,High School,Part-time,Divorced,No,No,Home,No,1
255344,56.0,84820,208294,597,70,3,5.29,60,0.50,High School,Self-employed,Married,Yes,Yes,Auto,Yes,0
255345,42.0,85109,60575,809,40,1,20.90,48,0.44,High School,Part-time,Single,Yes,Yes,Other,No,0
255346,62.0,22418,18481,636,113,2,6.73,12,0.48,Bachelor's,Unemployed,Divorced,Yes,No,Education,Yes,0

In [13]:
new_data.describe()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Default
count,255344.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000
mean,43.498473,82499.304597,127578.865512,574.264346,59.541976,2.501036,13.492773,36.025894,0.500212,0.116128
std,14.990245,38963.013729,70840.706142,158.903867,34.643376,1.117018,6.636443,16.969330,0.230917,0.320379
min,18.000000,15000.000000,5000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,0.000000
25%,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,0.000000
50%,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,0.000000
75%,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,0.000000
max,69.000000,149999.000000,249999.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,1.000000

In [31]:
new_data["Default"].value_counts()

Default
0    225694
1     29653
Name: count, dtype: int64

In [29]:
yes_data = new_data[new_data["Default"] == 1]
no_data  = new_data[new_data["Default"] == 0]

In [30]:
yes_data

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
2,46.0,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
5,25.0,90298,90448,720,18,2,22.72,24,0.10,High School,Unemployed,Single,Yes,No,Business,Yes,1
8,36.0,42053,92357,827,83,1,23.94,48,0.20,Bachelor's,Self-employed,Divorced,Yes,No,Education,No,1
11,28.0,149227,139759,375,56,3,5.84,36,0.80,PhD,Full-time,Divorced,No,No,Education,Yes,1
18,19.0,40718,78515,319,119,2,14.00,24,0.17,Bachelor's,Self-employed,Divorced,Yes,No,Education,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255310,65.0,111206,112192,315,3,3,20.17,36,0.63,High School,Unemployed,Married,Yes,Yes,Auto,No,1
255324,50.0,34641,108855,347,17,4,11.77,24,0.47,PhD,Unemployed,Divorced,Yes,No,Business,No,1
255333,22.0,45575,43355,545,99,1,21.86,12,0.52,PhD,Unemployed,Married,Yes,Yes,Education,No,1
255341,40.0,129890,116119,701,38,3,9.91,24,0.23,High School,Part-time,Divorced,Yes,No,Home,Yes,1
255343,32.0,51953,189899,511,14,2,11.55,24,0.21,High School,Part-time,Divorced,No,No,Home,No,1

In [32]:
min_size = min(len(yes_data), len(no_data))
min_size

29653

In [33]:
min_yes_data = yes_data.sample(min_size,random_state = 42)
min_no_data  = no_data.sample(min_size,random_state = 42)

In [34]:
min_no_data

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
191649,58.0,108264,61367,453,72,3,23.96,60,0.32,PhD,Full-time,Married,Yes,No,Business,No,0
243439,42.0,71611,31938,663,91,2,22.20,60,0.30,High School,Part-time,Married,No,No,Other,Yes,0
175764,31.0,30753,216354,740,38,2,22.94,12,0.18,PhD,Self-employed,Divorced,No,Yes,Auto,No,0
185368,40.0,130612,53234,539,18,3,12.83,60,0.65,Master's,Self-employed,Single,Yes,No,Education,No,0
68741,68.0,70154,243294,603,57,2,14.71,24,0.50,High School,Full-time,Married,Yes,Yes,Business,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141018,50.0,129003,209873,782,88,2,24.84,24,0.55,Bachelor's,Part-time,Divorced,No,No,Auto,No,0
25164,66.0,83074,101042,590,4,1,4.27,48,0.73,Master's,Self-employed,Single,No,No,Home,Yes,0
23196,68.0,16725,32990,640,67,3,24.44,24,0.58,Bachelor's,Full-time,Married,No,Yes,Home,No,0
117209,33.0,71765,213702,569,38,3,7.02,12,0.18,PhD,Unemployed,Divorced,No,No,Home,No,0
191726,23.0,116878,154673,394,62,4,13.29,36,0.89,Master's,Full-time,Single,Yes,No,Other,No,0

In [35]:
balanced_data = pd.concat([min_yes_data,min_no_data])

In [36]:
balanced_data

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
220566,21.0,128833,96957,317,83,2,23.92,48,0.23,PhD,Self-employed,Married,Yes,No,Auto,No,1
210651,23.0,17721,218809,459,10,1,23.62,48,0.11,High School,Unemployed,Married,No,Yes,Auto,Yes,1
230621,40.0,95675,237929,651,64,3,11.55,48,0.67,Bachelor's,Part-time,Divorced,No,No,Home,No,1
74658,47.0,29796,235097,650,100,1,19.63,12,0.74,Bachelor's,Part-time,Married,Yes,No,Business,Yes,1
224696,38.0,57457,149730,480,106,2,19.15,24,0.39,High School,Unemployed,Divorced,No,No,Other,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141018,50.0,129003,209873,782,88,2,24.84,24,0.55,Bachelor's,Part-time,Divorced,No,No,Auto,No,0
25164,66.0,83074,101042,590,4,1,4.27,48,0.73,Master's,Self-employed,Single,No,No,Home,Yes,0
23196,68.0,16725,32990,640,67,3,24.44,24,0.58,Bachelor's,Full-time,Married,No,Yes,Home,No,0
117209,33.0,71765,213702,569,38,3,7.02,12,0.18,PhD,Unemployed,Divorced,No,No,Home,No,0
191726,23.0,116878,154673,394,62,4,13.29,36,0.89,Master's,Full-time,Single,Yes,No,Other,No,0

In [39]:
balanced_data=  shuffle(balanced_data, random_state=42)

In [40]:
balanced_data

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
233937,22.0,111976,172949,457,22,1,13.50,60,0.73,High School,Self-employed,Single,No,Yes,Auto,No,1
229426,20.0,91246,233720,690,55,3,24.04,24,0.69,PhD,Unemployed,Married,Yes,No,Other,Yes,1
214204,18.0,116886,172974,591,10,3,8.48,36,0.53,High School,Full-time,Married,No,No,Other,Yes,1
91339,33.0,50824,134107,443,70,2,24.53,36,0.29,PhD,Part-time,Divorced,Yes,Yes,Auto,No,0
202096,53.0,115120,240301,459,40,2,8.24,36,0.31,PhD,Part-time,Single,No,No,Other,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67013,38.0,28356,60059,387,24,2,15.19,12,0.36,High School,Self-employed,Divorced,No,Yes,Other,Yes,1
109863,45.0,65657,202329,358,105,2,24.28,24,0.84,High School,Full-time,Married,Yes,No,Home,No,0
107832,64.0,81654,74257,358,99,2,23.26,36,0.20,High School,Full-time,Married,Yes,Yes,Business,No,0
240103,45.0,36989,107841,796,41,1,13.12,48,0.58,High School,Self-employed,Single,No,Yes,Other,Yes,1
117903,26.0,17905,90808,599,55,3,7.71,48,0.62,PhD,Part-time,Single,No,No,Home,Yes,1

In [41]:
reduced_data = balanced_data.sample(n=25000,random_state = 42)

In [42]:
reduced_data

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
42066,32.0,99695,209052,377,25,3,12.89,12,0.72,PhD,Part-time,Single,No,No,Auto,No,0
96440,41.0,71120,66634,840,6,4,17.99,48,0.61,High School,Self-employed,Married,No,Yes,Other,Yes,1
52394,22.0,138887,143679,686,36,2,5.52,48,0.90,PhD,Self-employed,Single,Yes,No,Other,Yes,1
229940,36.0,97625,147716,468,62,2,19.47,36,0.78,Master's,Unemployed,Married,No,No,Education,Yes,1
159215,59.0,146659,96938,453,119,3,5.41,12,0.71,Master's,Self-employed,Single,No,No,Auto,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101828,49.0,19089,133992,566,70,4,23.41,48,0.11,Master's,Self-employed,Divorced,No,No,Other,No,0
100620,44.0,126236,199469,820,98,2,12.26,24,0.47,PhD,Part-time,Single,Yes,No,Other,Yes,0
181003,37.0,66560,180082,747,21,2,8.49,36,0.18,Bachelor's,Full-time,Single,No,No,Other,No,1
163386,33.0,69734,245071,378,8,2,5.07,60,0.57,Master's,Full-time,Divorced,Yes,No,Education,Yes,1
247224,20.0,66156,189204,540,25,4,8.04,24,0.87,High School,Unemployed,Single,No,Yes,Other,Yes,0

In [45]:
reduced_data["Default"].value_counts()

Default
0    12557
1    12443
Name: count, dtype: int64

In [47]:
balanced_data["Default"].value_counts()

Default
1    29653
0    29653
Name: count, dtype: int64

In [55]:
final_yes = balanced_data[balanced_data['Default'] == 1].sample(n=25000, random_state=42)
final_no = balanced_data[balanced_data['Default'] == 0].sample(n=25000, random_state=42)

In [56]:
new_reduced_data = pd.concat([final_yes, final_no])

In [57]:
new_reduced_data = shuffle(new_reduced_data, random_state = 42)

In [58]:
new_reduced_data["Default"].value_counts()

Default
0    25000
1    25000
Name: count, dtype: int64